import { useCallback, useEffect, useState } from 'react';
import { BellRing, ChevronRight, CircleHelp, Edit3, KeyRound, LogOut, ShieldCheck, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { ErrorState, LoadingScreen } from '../components/Feedback';

function SettingRow({ icon: Icon, title, subtitle, value, to }) {
  const content = <><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-stone-100 text-stone-600"><Icon size={18} /></div><div className="min-w-0 flex-1"><p className="text-sm font-bold text-gray-900">{title}</p>{subtitle && <p className="mt-0.5 text-xs text-zinc-600">{subtitle}</p>}</div>{value && <span className="text-sm text-zinc-600">{value}</span>}<ChevronRight size={17} className="text-stone-400" /></>;
  return to ? <Link to={to} className="flex w-full items-center gap-3 border-b border-zinc-200 p-4 text-left last:border-0 hover:bg-orange-50/40">{content}</Link> : <div className="flex items-center gap-3 border-b border-zinc-200 p-4 last:border-0">{content}</div>;
}

export default function AccountPage() {
  const { logout, setUser } = useAuth(); const [profile, setProfile] = useState(null); const [error, setError] = useState('');
  const load = useCallback(() => { api.getAccount().then((data) => { setProfile(data.profile); setUser(data.profile); }).catch((requestError) => setError(requestError.message)); }, [setUser]);
  useEffect(load, [load]);
  if (!profile && !error) return <LoadingScreen />;
  if (error) return <ErrorState message={error} onRetry={() => { setError(''); load(); }} />;
  return <div className="mx-auto max-w-5xl space-y-6 animate-fade-up"><div><h1 className="page-title">Akun Profil</h1><p className="mt-1 text-sm text-zinc-600">Kelola identitas, keamanan, dan preferensi.</p></div>
    <section className="card overflow-hidden"><div className="bg-[#3A2418] p-5 text-white md:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-full bg-[#FFDDB5] font-['Plus_Jakarta_Sans'] text-2xl font-bold text-[#584239]">{profile.avatarDataUrl ? <img src={profile.avatarDataUrl} alt="Foto profil" className="size-full object-cover" /> : profile.displayName?.charAt(0)?.toUpperCase()}</div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-['Plus_Jakarta_Sans'] text-lg font-bold">{profile.workspaceName}</h2><span className="rounded-full bg-[#3C6451] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide">Terhubung</span></div><p className="mt-1 text-xs text-orange-100">{profile.workspaceType === 'shared' ? `${profile.displayName}${profile.partner ? ` & ${profile.partner.name}` : ''}` : 'Workspace Pribadi'}</p></div><Link className="btn-primary" to="/account/edit"><Edit3 size={17} />Ubah profil</Link></div></div>
      <div className="grid gap-0 md:grid-cols-2"><div className="p-5 md:p-6"><p className="mb-4 text-xs font-bold text-[#A13A00]">Detail {profile.displayName}</p><dl className="space-y-4 text-sm"><div><dt className="text-xs text-stone-600">Email</dt><dd className="mt-1 font-medium text-gray-900">{profile.email || '-'}</dd></div><div><dt className="text-xs text-stone-600">Nomor Handphone</dt><dd className="mt-1 font-medium text-gray-900">•••• {profile.phone?.slice(-4)}</dd></div><div><dt className="text-xs text-stone-600">Tanggal Lahir</dt><dd className="mt-1 font-medium text-gray-900">{profile.birthDate || '-'}</dd></div><div><dt className="text-xs text-stone-600">Kota</dt><dd className="mt-1 font-medium text-gray-900">{profile.city || '-'}</dd></div></dl></div><div className="border-t border-stone-200 p-5 md:border-l md:border-t-0 md:p-6"><p className="mb-4 text-xs font-bold text-stone-600">Detail Partner</p>{profile.partner ? <div className="flex items-center gap-3"><div className="grid size-12 place-items-center overflow-hidden rounded-full bg-orange-50 font-bold text-[#E86B32]">{profile.partner.avatarDataUrl ? <img src={profile.partner.avatarDataUrl} alt="" className="size-full object-cover" /> : profile.partner.name.charAt(0)}</div><div><p className="text-sm font-bold">{profile.partner.name}</p><p className="mt-1 text-xs text-stone-600">{profile.partner.phoneMasked}</p></div></div> : <p className="text-xs leading-5 text-stone-500">Belum terhubung dengan anggota lain. Gunakan chatbot untuk membuat kode pairing.</p>}</div></div>
    </section>
    <div className="grid gap-6 lg:grid-cols-2"><section><p className="mb-2 text-xs text-zinc-600">KEAMANAN</p><div className="card overflow-hidden"><SettingRow icon={KeyRound} title="Kode login WhatsApp" subtitle="Kode sekali pakai, berlaku 5 menit" /><SettingRow icon={ShieldCheck} title="Verifikasi WhatsApp" subtitle="Login tanpa kata sandi melalui akun WhatsApp" value="Aktif" /></div></section><section><p className="mb-2 text-xs text-zinc-600">PREFERENSI KEUANGAN</p><div className="card overflow-hidden"><SettingRow to="/account/preferences" icon={WalletCards} title="Mata uang" value="IDR (Rp)" /><SettingRow to="/account/preferences" icon={BellRing} title="Format Laporan" value={profile.reportPeriod === 'weekly' ? 'Mingguan' : 'Bulanan'} /><SettingRow to="/account/preferences" icon={BellRing} title="Pengingat" value={profile.remindersEnabled ? 'Aktif' : 'Nonaktif'} /></div></section><section><p className="mb-2 text-xs text-zinc-600">SUPPORT & ABOUT</p><div className="card overflow-hidden"><SettingRow to="/help" icon={CircleHelp} title="Pusat Bantuan" /><SettingRow to="/privacy" icon={ShieldCheck} title="Kebijakan Privasi" /></div></section><section><p className="mb-2 text-xs text-zinc-600">SESI</p><div className="card overflow-hidden"><button onClick={logout} className="flex w-full items-center gap-3 p-4 text-left text-red-700 hover:bg-red-50"><LogOut size={19} /><span className="text-sm font-bold">Keluar dari aplikasi</span></button></div></section></div>
  </div>;
}
