import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarDays, Plus, Save, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import { currentMonth, formatCurrency, monthLabel } from '../utils/formatters';
import { ErrorState, LoadingScreen } from '../components/Feedback';
import { notifySuccess } from '../utils/success';

const DEFAULT_BUDGET_CATEGORIES = ['Lainnya', 'Tagihan', 'Kebutuhan Pokok', 'Makanan & Minuman', 'Hiburan', 'Pendidikan', 'Transportasi', 'Belanja', 'Kesehatan'];

export default function BudgetPage() {
  const [month, setMonth] = useState(currentMonth()); const [budgets, setBudgets] = useState(null); const [newCategory, setNewCategory] = useState(''); const [error, setError] = useState(''); const [saved, setSaved] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(() => { api.getBudgets(month).then((data) => setBudgets(data.budgets)).catch((requestError) => setError(requestError.message)); }, [month]);
  useEffect(load, [load]);
  const totals = useMemo(() => (budgets || []).reduce((result, item) => ({ budget: result.budget + Number(item.amount || 0), spent: result.spent + Number(item.spent || 0) }), { budget: 0, spent: 0 }), [budgets]);
  function updateAmount(index, amount) { setBudgets((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, amount } : item)); setSaved(''); }
  function addCategory() { const category = newCategory.trim(); if (!category || budgets.some((item) => item.category.toLowerCase() === category.toLowerCase())) return; setBudgets([...budgets, { category, amount: 0, spent: 0, percentage: 0 }]); setNewCategory(''); notifySuccess('Kategori Berhasil Ditambahkan', 'Atur batas kategori baru, lalu pilih Simpan Penyesuaian untuk menerapkannya.'); }
  function removeCategory(index, category) { setBudgets(budgets.filter((_, itemIndex) => itemIndex !== index)); notifySuccess('Kategori Dihapus dari Penyesuaian', `${category} akan dinonaktifkan setelah Anda menyimpan penyesuaian budget.`); }
  async function save() { setBusy(true); setError(''); setSaved(''); try { const data = await api.saveBudgets(month, budgets.map(({ category, amount }) => ({ category, amount: Number(amount) }))); setBudgets(data.budgets); setSaved('Penyesuaian budget berhasil disimpan.'); notifySuccess('Budget Berhasil Disimpan', `Batas kategori untuk ${monthLabel(month)} sudah diperbarui.`); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }
  if (!budgets && !error) return <LoadingScreen />;
  if (error && !budgets) return <ErrorState message={error} onRetry={() => { setError(''); load(); }} />;
  return <div className="mx-auto max-w-5xl space-y-6 animate-fade-up"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Link className="btn-ghost p-2" to="/"><ArrowLeft size={20} /></Link><div><h1 className="page-title">Penyesuaian Budget</h1><p className="mt-1 text-xs text-stone-600">Atur batas setiap kategori untuk {monthLabel(month)}.</p></div></div><label className="relative"><CalendarDays className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-500" size={17} /><input type="month" className="input pl-10 sm:w-48" value={month} onChange={(event) => setMonth(event.target.value)} /></label></div>
    <section className="grid gap-3 sm:grid-cols-2"><div className="card p-5"><p className="text-xs text-stone-600">Total Budget Bulan Ini</p><p className="mt-2 font-['Plus_Jakarta_Sans'] text-2xl font-semibold text-[#2A1800]">{formatCurrency(totals.budget)}</p></div><div className="card p-5"><p className="text-xs text-stone-600">Total Pengeluaran</p><p className="mt-2 font-['Plus_Jakarta_Sans'] text-xl font-bold text-[#E86B32]">{formatCurrency(totals.spent)}</p></div></section>
    <section><h2 className="section-title mb-4">Kategori Budget</h2><div className="grid gap-3 md:grid-cols-2">{budgets.map((budget, index) => { const over = budget.spent > Number(budget.amount || 0); const percentage = Number(budget.amount) > 0 ? (budget.spent / Number(budget.amount)) * 100 : 0; return <article className="card p-4" key={budget.category}><div className="flex items-start justify-between gap-3"><div><h3 className="font-['Plus_Jakarta_Sans'] text-base font-semibold">{budget.category}</h3><p className={`mt-1 text-[10px] font-bold ${over ? 'text-red-700' : 'text-stone-600'}`}>{formatCurrency(budget.spent)} / {formatCurrency(budget.amount)}</p></div>{over && <span className="rounded-full bg-red-700 px-2 py-1 text-[10px] text-white">Melebihi Batas</span>}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-stone-200"><div className={`h-full rounded-full ${over ? 'bg-red-700' : 'bg-[#FCAB28]'}`} style={{ width: `${Math.min(percentage, 100)}%` }} /></div><label className="mt-4 block"><span className="label">Batas Bulanan Baru</span><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-stone-600">Rp</span><input className="input pl-10" type="number" min="0" value={budget.amount} onChange={(event) => updateAmount(index, event.target.value)} /></div></label>{!DEFAULT_BUDGET_CATEGORIES.includes(budget.category) && <button type="button" className="btn-ghost mt-2 text-red-700" onClick={() => removeCategory(index, budget.category)}><Trash2 size={15} />Hapus kategori</button>}</article>; })}</div></section>
    <section className="card p-4"><label className="label">Tambah Penyesuaian Kategori</label><div className="flex flex-col gap-2 sm:flex-row"><input className="input" maxLength={80} placeholder="Nama kategori baru" value={newCategory} onChange={(event) => setNewCategory(event.target.value)} /><button className="btn-secondary shrink-0" onClick={addCategory} disabled={!newCategory.trim()}><Plus size={17} />Tambah</button></div></section>
    {error && <p className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}{saved && <p className="rounded-xl bg-green-50 p-3 text-xs text-green-700">{saved}</p>}<div className="sticky bottom-24 flex justify-end lg:bottom-4"><button className="btn-primary w-full shadow-lg sm:w-auto" onClick={save} disabled={busy}><Save size={18} />{busy ? 'Menyimpan...' : 'Simpan Penyesuaian'}</button></div>
  </div>;
}
