import { ArrowLeft, MessageCircle, ShieldCheck, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function HelpPage() {
  return <div className="mx-auto max-w-3xl space-y-5 animate-fade-up"><div className="flex items-center gap-3"><Link className="btn-ghost p-2" to="/account"><ArrowLeft size={20} /></Link><div><h1 className="page-title">Pusat Bantuan</h1><p className="mt-1 text-xs text-stone-600">Panduan singkat menggunakan Klop Money.</p></div></div>
    <section className="grid gap-3 md:grid-cols-3"><article className="card p-5"><MessageCircle className="text-[#E86B32]" /><h2 className="mt-3 text-sm font-bold">Catat lewat WhatsApp</h2><p className="mt-2 text-xs leading-5 text-stone-600">Kirim contoh: “Beli makan 25rb” atau “Gaji 5jt”. Bot hanya memproses nomor yang terdaftar.</p></article><article className="card p-5"><WalletCards className="text-[#E86B32]" /><h2 className="mt-3 text-sm font-bold">Kelola melalui web</h2><p className="mt-2 text-xs leading-5 text-stone-600">Tambah, cari, edit, atau hapus transaksi milik sendiri dan atur budget bulanan.</p></article><article className="card p-5"><ShieldCheck className="text-[#E86B32]" /><h2 className="mt-3 text-sm font-bold">Jaga keamanan akun</h2><p className="mt-2 text-xs leading-5 text-stone-600">Kode login berlaku lima menit, hanya sekali pakai, dan tidak boleh dibagikan.</p></article></section>
    <section className="card p-5"><h2 className="section-title">Perintah penting</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-bold">login web</dt><dd className="text-xs text-stone-600">Meminta kode login 6 digit.</dd></div><div><dt className="font-bold">rekap hari ini / minggu ini / bulan ini</dt><dd className="text-xs text-stone-600">Melihat ringkasan transaksi sesuai periode.</dd></div><div><dt className="font-bold">pasangkan saya</dt><dd className="text-xs text-stone-600">Membuat kode pairing untuk pasangan.</dd></div></dl></section>
  </div>;
}
