import { useEffect, useState } from 'react';
import { ArrowDownLeft, ArrowLeft, ArrowUpRight, LockKeyhole, Save, UsersRound } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../services/api';
import { ErrorState, LoadingScreen } from '../components/Feedback';
import { toDateTimeLocal } from '../utils/formatters';
import { notifySuccess } from '../utils/success';

const fallbackCategories = ['Makanan & Minuman', 'Transportasi', 'Kebutuhan Pokok', 'Belanja', 'Tagihan', 'Kesehatan', 'Pendidikan', 'Hiburan', 'Gaji', 'Bonus', 'Transfer', 'Lainnya'];

export default function TransactionFormPage() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate();
  const [form, setForm] = useState({ amount: '', type: 'Pengeluaran', category: 'Kebutuhan Pokok', scope: 'shared', description: '', timestamp: toDateTimeLocal() });
  const [categories, setCategories] = useState(fallbackCategories);
  const [loading, setLoading] = useState(editing); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api.getCategories().then((data) => setCategories(data.categories)).catch(() => {}); }, []);
  useEffect(() => { if (!editing) return; api.getTransaction(id).then(({ transaction }) => { if (!transaction.canEdit) throw new Error('Transaksi ini tidak dapat diedit.'); setForm({ amount: String(transaction.amount), type: transaction.type, category: transaction.category, scope: transaction.scope, description: transaction.description, timestamp: toDateTimeLocal(transaction.timestamp) }); }).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)); }, [editing, id]);
  function update(key, value) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const payload = { ...form, amount: Number(form.amount), timestamp: new Date(form.timestamp).toISOString() }; const data = editing ? await api.updateTransaction(id, payload) : await api.createTransaction(payload); notifySuccess(editing ? 'Transaksi Berhasil Diperbarui' : 'Transaksi Berhasil Ditambahkan', editing ? 'Perubahan transaksi sudah tersimpan dan langsung diterapkan pada laporan.' : 'Transaksi baru sudah tersimpan dan masuk ke laporan keuangan.'); navigate(`/transactions/${data.transaction.id}`, { replace: true }); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }
  if (loading) return <LoadingScreen />;
  if (error && editing && !form.amount) return <ErrorState message={error} />;
  return <div className="mx-auto max-w-4xl animate-fade-up"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-3"><Link className="btn-ghost p-2" to={editing ? `/transactions/${id}` : '/transactions'}><ArrowLeft size={20} /></Link><div><h1 className="page-title">{editing ? 'Edit Transaksi' : 'Tambah Transaksi Baru'}</h1><p className="mt-1 text-xs text-stone-600">Isi data secara jelas agar laporan tetap akurat.</p></div></div></div>
    <form onSubmit={submit} className="card p-4 md:p-7"><div className="grid gap-6 lg:grid-cols-2"><div className="space-y-5"><label><span className="label">Nominal</span><div className="relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-sm font-semibold text-stone-600">Rp</span><input className="input !min-h-14 pl-12 font-['Plus_Jakarta_Sans'] text-xl font-bold" type="number" min="1" inputMode="numeric" placeholder="450.000" value={form.amount} onChange={(event) => update('amount', event.target.value)} required /></div></label><fieldset><legend className="label">Tipe Transaksi</legend><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => update('type', 'Pengeluaran')} className={`flex min-h-20 flex-col items-start justify-center rounded-xl border p-3 text-left ${form.type === 'Pengeluaran' ? 'border-amber-500 bg-amber-50 text-amber-700' : 'border-stone-300 bg-white text-stone-600'}`}><ArrowUpRight size={20} /><strong className="mt-1 text-sm">Pengeluaran</strong><span className="text-[10px]">Debit / uang keluar</span></button><button type="button" onClick={() => update('type', 'Pemasukan')} className={`flex min-h-20 flex-col items-start justify-center rounded-xl border p-3 text-left ${form.type === 'Pemasukan' ? 'border-green-600 bg-green-50 text-green-700' : 'border-stone-300 bg-white text-stone-600'}`}><ArrowDownLeft size={20} /><strong className="mt-1 text-sm">Pemasukan</strong><span className="text-[10px]">Kredit / uang masuk</span></button></div></fieldset><label><span className="label">Kategori</span><select className="input" value={form.category} onChange={(event) => update('category', event.target.value)}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label></div>
      <div className="space-y-5"><fieldset><legend className="label">Pos Transaksi</legend><div className="space-y-2"><button type="button" onClick={() => update('scope', 'shared')} className={`flex w-full items-center gap-3 rounded-xl border p-3.5 text-left ${form.scope === 'shared' ? 'border-[#E86B32] bg-orange-50' : 'border-stone-300'}`}><UsersRound className="text-[#E86B32]" size={21} /><span><strong className="block text-sm text-stone-900">Pos Bersama</strong><span className="text-[10px] text-stone-600">Detail dapat dilihat anggota workspace.</span></span></button><button type="button" onClick={() => update('scope', 'personal')} className={`flex w-full items-center gap-3 rounded-xl border p-3.5 text-left ${form.scope === 'personal' ? 'border-[#E86B32] bg-orange-50' : 'border-stone-300'}`}><LockKeyhole className="text-[#E86B32]" size={21} /><span><strong className="block text-sm text-stone-900">Pos Pribadi</strong><span className="text-[10px] text-stone-600">Anggota lain hanya melihat nominal.</span></span></button></div></fieldset><label><span className="label">Tanggal & Waktu</span><input className="input" type="datetime-local" value={form.timestamp} onChange={(event) => update('timestamp', event.target.value)} required /></label><label><span className="label">Keterangan</span><textarea className="input min-h-28 resize-y" maxLength={500} placeholder="Contoh: Belanja mingguan sayur & buah" value={form.description} onChange={(event) => update('description', event.target.value)} /></label></div></div>
      {error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="mt-7 flex flex-col-reverse gap-3 border-t border-stone-200 pt-5 sm:flex-row sm:justify-end"><Link className="btn-secondary" to={editing ? `/transactions/${id}` : '/transactions'}>Batal</Link><button className="btn-primary" disabled={busy}><Save size={17} />{busy ? 'Menyimpan...' : editing ? 'Simpan Perubahan' : 'Simpan Transaksi'}</button></div>
    </form></div>;
}
