import { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronRight, Edit3, Filter, LockKeyhole, Plus, Search, UsersRound } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { api } from '../services/api';
import { currentMonth, formatCurrency, formatDate, monthLabel } from '../utils/formatters';
import { ErrorState, LoadingScreen, EmptyState } from '../components/Feedback';
import { TransactionCard, TypeBadge } from '../components/TransactionItem';

function ContributionCard({ contribution }) {
  return <div className="panel flex min-w-[260px] flex-1 items-center gap-3 p-4"><div className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-full bg-[#FFDDB5] font-bold text-[#584239]">{contribution.avatarDataUrl ? <img src={contribution.avatarDataUrl} alt="" className="size-full object-cover" /> : contribution.name?.charAt(0) || 'P'}</div><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold text-stone-900">{contribution.name}</h3><p className="mt-0.5 text-xs text-stone-600">{contribution.count} transaksi</p></div><div className="text-right text-xs"><p className="text-stone-600">Debit <strong className="text-amber-500">{formatCurrency(contribution.expense, true)}</strong></p><p className="mt-1 text-stone-600">Kredit <strong className="text-green-600">{formatCurrency(contribution.income, true)}</strong></p></div></div>;
}

export default function TransactionsPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const search = searchParams.get('q') || '';
  const [month, setMonth] = useState(currentMonth()); const [scope, setScope] = useState('all'); const [page, setPage] = useState(1);
  const [data, setData] = useState(null); const [error, setError] = useState('');
  const load = useCallback(() => { Promise.all([api.getTransactions(month), api.getDashboard(month)]).then(([transactions, dashboard]) => setData({ transactions: transactions.transactions, contributions: dashboard.contributions })).catch((requestError) => setError(requestError.message)); }, [month]);
  useEffect(load, [load]);
  const filtered = useMemo(() => (data?.transactions || []).filter((item) => (scope === 'all' || item.scope === scope) && (!search || `${item.description} ${item.category}`.toLowerCase().includes(search.toLowerCase()))), [data, scope, search]);
  const pageSize = 25; const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const safePage = Math.min(page, totalPages); const visible = filtered.slice((safePage - 1) * pageSize, safePage * pageSize);
  if (!data && !error) return <LoadingScreen />;
  if (error) return <ErrorState message={error} onRetry={() => { setError(''); load(); }} />;
  return <div className="space-y-7 animate-fade-up">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="page-title">Transaksi</h1><p className="mt-1 text-xs text-stone-600">Riwayat pengeluaran bersama dan pribadi.</p></div><Link className="btn-primary hidden sm:inline-flex" to="/transactions/new"><Plus size={18} />Transaksi Baru</Link></div>
    <section><div className="mb-3 flex items-center gap-2"><UsersRound size={20} className="text-[#E86B32]" /><h2 className="section-title">Kontribusi Bulan Ini</h2></div><div className="scrollbar-none flex gap-3 overflow-x-auto pb-2">{data.contributions.length ? data.contributions.map((item) => <ContributionCard key={item.reporter} contribution={item} />) : <p className="text-sm text-stone-500">Belum ada kontribusi bulan ini.</p>}</div></section>
    <section className="card overflow-hidden"><div className="border-b border-stone-200 p-4 md:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="section-title">Daftar Transaksi</h2><p className="mt-1 text-xs text-stone-600">Menampilkan seluruh riwayat pengeluaran bersama & pribadi</p></div><div className="grid gap-2 sm:grid-cols-3"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-500" size={16} /><input className="input pl-9" placeholder="Cari..." value={search} onChange={(event) => { const next = new URLSearchParams(searchParams); if (event.target.value) next.set('q', event.target.value); else next.delete('q'); setSearchParams(next, { replace: true }); }} /></label><label className="relative"><CalendarDays className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-500" size={16} /><input type="month" className="input pl-9" value={month} onChange={(event) => setMonth(event.target.value)} /></label><label className="relative"><Filter className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-500" size={16} /><select className="input appearance-none pl-9" value={scope} onChange={(event) => setScope(event.target.value)}><option value="all">Semua Pos</option><option value="shared">Pos Bersama</option><option value="personal">Pos Pribadi</option></select></label></div></div><p className="mt-3 text-[10px] font-semibold text-[#A13A00]">{monthLabel(month)} • {filtered.length} transaksi</p></div>
      {!filtered.length ? <EmptyState title="Transaksi tidak ditemukan" description="Ubah filter atau tambahkan transaksi baru." /> : <><div className="md:hidden">{visible.map((transaction) => <TransactionCard key={transaction.id} transaction={transaction} />)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[850px] border-collapse text-left"><thead className="bg-orange-100 text-xs"><tr><th className="px-5 py-4">Tanggal</th><th className="px-5 py-4">Tipe & Kategori</th><th className="px-5 py-4">Keterangan</th><th className="px-5 py-4 text-right">Nominal</th><th className="px-5 py-4">Dibuat oleh</th><th className="px-5 py-4">Pos</th><th className="px-5 py-4" /></tr></thead><tbody>{visible.map((transaction) => <tr key={transaction.id} className="border-t border-stone-200 text-xs hover:bg-orange-50/40"><td className="whitespace-nowrap px-5 py-4 text-stone-600">{formatDate(transaction.timestamp)}</td><td className="px-5 py-4"><TypeBadge type={transaction.type} /><div className="mt-1 text-[10px] text-stone-500">{transaction.category}</div></td><td className="max-w-52 truncate px-5 py-4 font-bold text-stone-900">{transaction.description}</td><td className="px-5 py-4 text-right font-['Plus_Jakarta_Sans'] text-sm font-bold">{formatCurrency(transaction.amount)}</td><td className="px-5 py-4 text-stone-600">Pengguna {String(transaction.reporter).replace(/\D/g, '').slice(-4)}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-1 rounded-full bg-stone-100 px-2 py-1 text-[10px] text-stone-700">{transaction.scope === 'personal' && <LockKeyhole size={11} />}{transaction.scope === 'personal' ? 'Pribadi' : 'Bersama'}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-1">{transaction.canEdit && <Link className="btn-ghost !min-h-8 p-2" to={`/transactions/${transaction.id}/edit`} aria-label="Edit"><Edit3 size={15} /></Link>}<Link className="btn-ghost !min-h-8 p-2" to={`/transactions/${transaction.id}`} aria-label="Detail"><ChevronRight size={16} /></Link></div></td></tr>)}</tbody></table></div>{totalPages > 1 && <div className="flex items-center justify-between border-t border-stone-200 p-4"><span className="text-xs text-stone-600">Halaman {safePage} dari {totalPages}</span><div className="flex gap-2"><button className="btn-secondary min-h-9 px-3" onClick={() => setPage(Math.max(1, safePage - 1))} disabled={safePage === 1}>Sebelumnya</button><button className="btn-secondary min-h-9 px-3" onClick={() => setPage(Math.min(totalPages, safePage + 1))} disabled={safePage === totalPages}>Berikutnya</button></div></div>}</>}
    </section>
  </div>;
}
